services:
  postgis:
      container_name: postgis
      environment:
        - POSTGRES_PASSWORD=12345678
        - POSTGRES_DB=CanopyNavigator
        - POSTGRES_USER=postgres
      ports:
        - 5432:5432
      image: postgis/postgis
networks:
  pgnet:
      external: true
      name: pgnet